#!/usr/bin/env bash
#
# Starts Dockerized FTP test servers (FTP, FTPS and SFTP).
#
# @author mikko.parviainen@fmi.fi, 2023
#

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

SCRIPT_BASE_DIR="$(dirname "${BASH_SOURCE[0]}")"

source "${SCRIPT_BASE_DIR}/common-functions.sh"

function main() {
  cd "${SCRIPT_BASE_DIR}"

  generate_private_key_and_certificate_for_ftps
  generate_lftp_client_configuration_for_ftps
  generate_test_files
  remove_previously_known_localhost_sftp_host_key
  start_ftp_servers
}

main "$@"
