name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: ShellCheck
      run: |
        find . -path ./.git -prune -o -type f -print0 | \
          xargs --no-run-if-empty --null --max-args=1 \
            sed --quiet '/^#!.*sh$/F;q' | \
              xargs --no-run-if-empty \
                shellcheck --external-sources --check-sourced

    - name: Setup
      ports:
        - 2221
        - 2231
        - 2222
        - 21000-21010
        - 22000-22010
      run: |
        id
        ./setup &
        # Give some time for the containers to start
        sleep 15
        echo -e "ls\nbye" > ftp-commands

    - name: FTP connection test
      run: |
        cat ftp-commands | \
          ftp -d -q 10 -v ftp://ftpuser:ftppass@localhost:2221

    - name: FTPS connection test
      run: |
        echo "TODO"

    - name: SFTP connection test
      run: |
        export SSHPASS=ftppass
        cat ftp-commands | \
          sshpass -e sftp -o StrictHostKeyChecking=accept-new -P 2222 ftpuser@localhost
        unset SSHPASS

    - name: Teardown
      run: |
        ./teardown
        rm --force ftp-commands
