name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: ShellCheck
      run: |
        find . -path ./.git -prune -o -type f -print0 | \
          xargs --no-run-if-empty --null --max-args=1 \
            sed --quiet '/^#!.*sh$/F;q' | \
              xargs --no-run-if-empty \
                shellcheck --external-sources --check-sourced

    - name: Setup
      run: |
        sudo apt-get install --yes lftp
        echo -e "ls\nbye" > ftp-commands
        ./setup
        # Give some time for the containers to start
        sleep 15

    - name: FTP connection test
      if: always()
      run: |
        cat << EOF > ~/.lftprc
        set ftp:passive-mode yes
        set net:max-retries 2
        set net:timeout 2
        set dns:fatal-timeout 2
        set torrent:timeout 2
        set xfer:timeout 2
        debug 1
        EOF
        cat ftp-commands | \
          lftp -u ftpuser,ftppass ftp://localhost:2221
        rm --force ~/.lftprc

    - name: FTPS connection test
      if: always()
      run: |
        cat << EOF > ~/.lftprc
        set ftp:ssl-auth TLS
        set ftp:ssl-force true
        set ftp:ssl-protect-list yes
        set ftp:ssl-protect-data yes
        set ftp:ssl-protect-fxp yes
        set ftp:passive-mode yes
        set ssl:verify-certificate no
        set net:max-retries 2
        set net:timeout 2
        set dns:fatal-timeout 2
        set torrent:timeout 2
        set xfer:timeout 2
        debug 1
        EOF
        cat ftp-commands | \
          lftp -u ftpuser,ftppass ftp://localhost:2231
        rm --force ~/.lftprc

    - name: SFTP connection test
      if: always()
      run: |
        export SSHPASS=ftppass
        cat ftp-commands | \
          sshpass -e sftp -o StrictHostKeyChecking=accept-new -P 2222 ftpuser@localhost
        unset SSHPASS

    - name: Teardown
      if: always()
      run: |
        ./teardown
        rm --force ftp-commands
